### ISSUE TITLE
undefined symbol: xnd_split

### ISSUE THREAD

**Issue by davidbrochart** [plures/xnd-all#16]
```bash
git clone https://github.com/plures/xnd-all.git
cd xnd-all
python setup.py install
python
```

```pycon
>>> import xnd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/david/soft/anaconda3/lib/python3.6/site-packages/xnd/__init__.py", line 49, in <modulle>
    from ._xnd import Xnd, XndEllipsis
ImportError: /home/david/soft/anaconda3/lib/python3.6/site-packages/xnd/_xnd.cpython-36m-x86_64-linux-gnu.so: undefined symbol: xnd_split
```

**Comment by davidbrochart** [comment]
Don't mix conda and non-conda builds.
